server:
  port: 8080
spring:
    datasource:
        druid-master:
            type: com.alibaba.druid.pool.DruidDataSource
            driver-class-name: com.mysql.jdbc.Driver
            jdbc-url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
            username: root
            password: 123456
            maxActive: 1000
            initialSize: 1
            minIdle: 1
            maxOpenPreparedStatements: -1
            validation-query: SELECT 1
            test-on-borrow: false
            test-while-idle: true
            time-between-eviction-runs-millis: 300000
            min-evictable-idle-time-millis: 600000

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check
master:
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
    mybatis:
        mapper-locations: classpath*:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
        type-aliases-package: com.srx.blog.domain #注意：对应实体类的路径
    product:
        workerId: 20
        datacenterId: 20